### ISSUE TITLE
README "Python Library Use Example" should call permutationtest, not permutation_test

### ISSUE THREAD

**Issue by jesszwang** [cmohl2013/permutation_test#1]
First off, thanks for making this Python package!

I was trying to get started with it, and followed the example in your readme. However, p.permutation_test() was not a valid function. Had to check out this repo for the package and see that the correct function to use was actually p.permutationtest():

https://github.com/cmohl2013/permutation_test/blob/master/README.rst#python-library-use-example

**Comment by cmohl2013** [comment]
thanks again! I close the issue now. I updated one year ago but forgot to close it.
